name: manage-azure-policy-a4fd6c3e
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Require_tag_and_value_on_resource_groups_4592bacb-67b5-4849-9771-0c9b044801ff/**'
#      - 'initiatives/mg-kwb-initiative_d19a4604a2f34da4a6634101/**'
#      - .github/workflows/manage-azure-policy-a4fd6c3e.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_a4fd6c3e}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Require_tag_and_value_on_resource_groups_4592bacb-67b5-4849-9771-0c9b044801ff/**
          initiatives/mg-kwb-initiative_d19a4604a2f34da4a6634101/**
